<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disabled</ImplicitUsings>
	  <PublishSingleFile>true</PublishSingleFile>
	  <SelfContained>true</SelfContained>
	  <RuntimeIdentifier>win-x86</RuntimeIdentifier>
	  <PublishReadyToRun>true</PublishReadyToRun>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	  <ApplicationIcon>winanimico.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="segoe_slboot.ttf" />
    <None Remove="winanimico.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="segoe_slboot.ttf" />
    <EmbeddedResource Include="winanimico.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>